# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'WALL-E' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WALL-E
  pod 'SwiftSocket'

end
